version: 2.1

jobs:
  build-docker:
    docker:
      - image: katherinetrammell/ci-image
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  build-docker-workflow:
    jobs:
      - build-docker
